<a href="https://colab.research.google.com/github/2303a52483/23CSBTB44/blob/main/2303A52483.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
import pandas as pd
list=np.array([1,2,3,4,5])
list=pd.array([1,2,3,4,5])
print(list)


<IntegerArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: Int64


In [25]:
list1=np.array([1,2,3,4])
list2=np.array([2,4,6,8])
mul=(list1*list2)
print(mul)
div=list1/list2
print(div)
print(np.power(list1,list2))
print(list1+list2)

[ 2  8 18 32]
[0.5 0.5 0.5 0.5]
[    1    16   729 65536]
[ 3  6  9 12]


In [24]:
print(np.sin(2))
print(np.log(2))
print(np.log2(2))
print(np.exp(2))


0.9092974268256817
0.6931471805599453
1.0
7.38905609893065
